#=========================================================================
# LVS using netgen
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: netgen-lvs-gds

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_extracted.spice
  - design.lvs.v

outputs:
  - lvs_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: user_proj_example

commands: 
  - sh run_lvs.sh

